config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'home#new_index'

  get '/tos'                       => 'home#tos'
  get 'privacy-policy'             => 'home#privacy_policy'

  post   "/concierge/process"             => "home#concierge_process", as: :concierge_process
  
  get    "/admin"                         => "admin#index",            as: :admin
  get    "/admin/twitter"                 => "admin#twitter",          as: :twitter
  post   "/admin/twitter"                 => "admin#twitter"
  get    "/admin/twitter/:id/followers"   => "admin#twitter_followers"
  get    "/admin/twitter/:id/job"         => "admin#twitter_job_rerun"
  get    "/admin/twitter/tweets/:id"      => "admin#twitter_tweets" 

  get    "/admin/inbound"                 => "admin#inbound",          as: :inbound
  post   "/admin/inbound"                 => "admin#inbound"
  get    "/admin/inbound/:id/run"         => "admin#inbound_crawl"
  get    "/admin/inbound/:id/update"      => "admin#inbound_crawl"
  get    "/admin/inbound/:id"             => "admin#ajax_inbound_user_modal", format: "js"
  get    "/admin/twitter-tweets-all"      => "admin#twitter_tweets_all",      format: "json"

  post   "/admin/tracking/:candy_token/bounce"         =>  "admin/aws#bounce"
  post   "/admin/tracking/:candy_token/complaint"      =>  "admin/aws#complaint"
  post   "/admin/tracking/:candy_token/delivered"      =>  "admin/aws#delivered"
  
  get    "/admin/aws/all"                               =>  "admin/aws#view_all"
  get    "/admin/aws/bounce"                            =>  "admin/aws#view_bounce"
  get    "/admin/aws/complaints"                        =>  "admin/aws#view_complaint"
  get    "/admin/aws/delivered"                         =>  "admin/aws#view_delivered"

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == "sidekiq" && password == "sidekiq1905!"
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"
  
  get    "*unmatched_route"               => "home#no_route_match_error"
  end

app/views/admin/_ajax_inbound_user_modal.html.erb
<%# Modal Window for Inbound User Details %>
<div class="modal fade" aria-labelledby="InboundUser" aria-hidden="true">
  <div class="modal-vertical-align-helper">
    <div class="modal-dialog modal-vertical-center">
      <div class="modal-content">
        <div class="top-strip"></div>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="opacity: 0.8"><%= image_tag "/assets/cancel.png", width: "24", height: "24" %></button>
          <h4 class="modal-title"><%= @inbound_user.name.to_s.titleize %></h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-xs-12">
              <div class="panel panel-default sharp-corners">
                <div class="panel-body">
                  <table style="position: absolute;right: 17px;top: 2px;">
                    <tbody>
                      <% unless @inbound_user.image_url.blank? %>
                        <tr>
                          <td>
                            <img src="<%= @inbound_user.image_url.to_s %>" alt="Inbound_user_<%= @inbound_user.userid.to_s %>" width="150" id="inbound_user_image" />
                          </td>
                        </tr>
                      <% end %>
                      <% if !@inbound_user.inbound_link.blank? %>
                        <tr>
                          <td class="pull-right half-spaced">
                            <a href="<%= @inbound_user.inbound_link %>" rel="nofollow" target="_blank">
                              <img src='/assets/inbound.png' width='30'/>
                            </a>
                          </td>
                        </tr>
                      <% end %>
                      <% if !@inbound_user.twitter_link.blank? %>
                        <tr>
                          <td class="pull-right half-spaced">
                            <a href="<%= @inbound_user.twitter_link %>" rel="nofollow" target="_blank">
                              <img src='/assets/twitter.png' width='30'/>
                            </a>
                          </td>
                        </tr>
                      <% end %>
                      <% if !@inbound_user.facebook_link.blank? %>
                        <tr>
                          <td class="pull-right half-spaced">
                            <a href="<%= @inbound_user.facebook_link %>" rel="nofollow" target="_blank">
                              <img src='/assets/facebook.png' width='30'/>
                            </a>
                          </td>
                        </tr>
                      <% end %>
                      <% if !@inbound_user.linkedin_link.blank? %>
                        <tr>
                          <td class="pull-right half-spaced">
                            <a href="<%= @inbound_user.linkedin_link %>" rel="nofollow" target="_blank">
                              <img src='/assets/linkedin.png' width='30'/>
                            </a>
                          </td>
                        </tr>
                      <% end %>
                      <% if !@inbound_user.googleplus_link.blank? %>
                        <tr>
                          <td class="pull-right half-spaced">
                            <a href="<%= @inbound_user.googleplus_link %>" rel="nofollow" target="_blank">
                              <img src='/assets/googleplus.png' width='30'/>
                            </a>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <table class="table">
                    <tbody>
                      <tr>
                        <td style="border: 0 none;">Name </td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.name.to_s %><br/>(<% unless @inbound_user.my_link.blank? then %><a href="<%= @inbound_user.my_link.to_s %>" target="_blank">My Link</a><% end %>)</td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Karma </td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.karma.to_s %></td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Number of followers</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.number_followers.to_s %></td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Number of following</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.number_following.to_s %></td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Designation</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.designation.to_s %> <%= @inbound_user.company.blank? ? "" : "@<a href=\"#{@inbound_user.company_link.blank? ? "#" : @inbound_user.company_link.to_s}\" target=\"_blank\">#{@inbound_user.company.to_s}</a>".html_safe %></td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Location</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;"><%= @inbound_user.location.to_s %></td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Following</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;">
                          <% if @inbound_user.following %>
                            <img src="/assets/yes.png" width="20" alt="Yes" />
                          <% else %>
                            <img src="/assets/no.png" width="20" alt="No" />
                          <% end %>
                        </td>
                      </tr>
                      <tr>
                        <td style="border: 0 none;">Follow back</td>
                        <td style="border: 0 none;">:</td>
                        <td style="border: 0 none;">
                          <% if @inbound_user.follower %>
                            <img src="/assets/yes.png" width="20" alt="Yes" />
                          <% else %>
                            <img src="/assets/no.png" width="20" alt="No" />
                          <% end %>
                        </td>
                      </tr>
                      <% unless @inbound_user.badges.blank? %>
                        <tr>
                          <td style="border: 0 none;">Badges (<%= @inbound_user.number_badges.to_s %>)</td>
                          <td style="border: 0 none;">:</td>
                          <td style="border: 0 none;">
                            <% @inbound_user.badges.split(",").each do |badge| %>
                              <span class='badge'><%= badge.to_s.strip %></span>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/inbound.html.erb
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
  <tbody>
    <tr>
      <td valign="middle">
        <div class="container full-spaced full-spaced-bottom">
          <div class="row">
            <div class="col-lg-6 col-md-7 col-sm-8 col-xs-11 col-centered">
              <h2 class="text-center no-margin">Inbound.org Portal</h2>
              <p class="text-center"><strong>Download all users : &nbsp;<a href="./inbound.csv" download="Inbound_<%= Time.now.strftime('%b_%d_%Y_%H_%m_%S').to_s %>.csv">CSV</a> | <a href="./inbound.xls" download="Inbound_<%= Time.now.strftime('%b_%d_%Y_%H_%m_%S').to_s %>.xls">XLS</a></strong></p>
              <p class="text-center no-margin">Use the tabs below to toggle between Inbound Links & Inbound Users Datatable.</p> 
            </div>
          </div>
          <br><br>
          <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <ul class="nav nav-tabs nav-justified">
                <li class="active"><a data-toggle="tab" href="#links">Inbound Links</a></li>
              <% unless @inbound_links.blank? %>
                <li><a data-toggle="tab" href="#table">Inbound Users Table</a></li>
              <% end %>
            </ul>
            </div>
          </div>  
          <div class="tab-content">         
          
           <div id="links" class="tab-pane fade in active">
            <div class="row">
              <div class="col-md-9 col-sm-10 col-xs-12 col-centered spaced">
              <%= form_tag inbound_path, method: :post, id: "inbound_form", class: "spaced spaced-bottom" do %>
                <div class="input-group">
                  <%= text_field_tag :inbound_search_query_link, "" , class: "form-control sharp-corners ", required: true, placeholder: "Paste an inbound.org search URL here.", "data-parsley-error-message" => "Please enter valid search query link.", "data-parsley-errors-container" => "#inbound_username_error" %>
                  <span class="input-group-btn">
                    <%= submit_tag "Submit link", id: "inbound_form_submit", class: "btn btn-default sharp-corners" %>
                  </span>
                </div>
                <div id="inbound_username_error"></div>
              <% end %> 
          </div></div>
          <% unless @inbound_links.blank? %>
            <% is_processing = @inbound_links.where(is_processing: true).exists? %>
            <div class="row">
              <div class="col-md-9 col-sm-10 col-xs-12 col-centered spaced">
                <% if is_processing %>
                  <div class="half-spaced"><p style="color: red;font-size: 14px;">Crawler is running. We can run only one crawl at a time</p></div>
                <% end %>
                <div class="table-responsive half-spaced">
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>Inbound Link</th>
                        <th class="text-center" width="100">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @inbound_links.each do |t| %>
                        <tr>
                          <td>
                            <a href="<%= t.link %>" target="_blank"><%= t.link.to_s.truncate(80) %></a>
                            <% unless t.date_processed.blank? %>
                              <div>Date processed: <%= t.date_processed.strftime('%b %d %Y') %></div>
                            <% end %>
                          </td>
                          <td class="text-center">
                            <% if t.date_processed.blank? %>
                              <a href="<%= is_processing ? "#" : "/admin/inbound/#{t.id.to_s}/run" %>" class="btn btn-success <%= is_processing ? "disabled" : "" %>">Run</a>
                            <% elsif t.date_processed == Date.today %>
                              <p style="color: red;">Updated!</p>
                            <% elsif t.date_processed < Date.today %>
                              <a href="<%= is_processing ? "#" : "/admin/inbound/#{t.id.to_s}/update" %>" class="btn btn-primary <%= is_processing ? "disabled" : "" %>">Update</a>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
           </div> 
          <% end %>
          <% unless @inbound_users.blank? %>
          <div id="table" class="tab-pane fade in">
            <div class="row">
              <div class="col-md-9 col-sm-10 col-xs-12 col-centered" id="inbound_datatable">
                <div class="row spaced">
                  <div class="col-sm-12 col-md-6">
                    <input id="inboundFollowerSearch" type="text" placeholder="Search" />
                    <select id="inboundFollowerSearch2" class="btn btn-default dropdown-toggle"> 
                      <option  value="1"> Name & Username </option>
                      <option  value="2"> Job & Designation</option>
                      <option  value="3"> Location </option>
                      <option  value="4"> Badges </option>
                      <option  value="5"> Karma </option>
                      <option  value="6"> Followers </option>
                      <option  value="7"> Following </option>
                      <option  value="8"> Number of badges </option>
                    </select>
                  </div>
                  <div class="col-sm-12 col-md-6 text-right">
                    <div class="dropdown" style="padding-top: 7px;">
                      <label id="dataTablesInfo"></label>
                      <button class="btn dropdown-toggle custom-dropdown-btn" type="button" id="dataTablesLength" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span></button>
                      <ul class="dropdown-menu custom-dropdown-menu" aria-labelledby="dataTablesLength">
                        <li style="padding: 6px 0px;">Show up to:</li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(10);">&nbsp;&nbsp;10 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(20);">&nbsp;&nbsp;20 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(40);">&nbsp;&nbsp;40 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(80);">&nbsp;&nbsp;80 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(100);">&nbsp;&nbsp;100 items</a></li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-sm-12 col-md-4 col-md-offset-8 text-right">
                    <a class="btn btn-primary inbound-user-update">Refresh table</a>                   
                  </div>
                </div>
                <table id="inbound_followers" class="table table-bordered" data-source="/admin/inbound.json">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Following</th>
                      <th>Follow Back</th>
                      <th>Date Processed</th>
                      <th class="text-center" style="padding-right: 0px; text-align: left;">Social Media Links</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>  
          <% end %>
        </div>
      </td>
    </tr>
  </tbody>
</table>

</div>
<%# Ajax Inbound User Detail Modal %>
<div id="inbound_user_modal"></div>

app/views/admin/inbound.js.erb
$("#inbound_user_modal").html("<%= escape_javascript(render partial: 'ajax_inbound_user_modal') %>");
$("#inbound_user_modal > div.modal").modal({
  backdrop: "static",
  keyboard: false
});

app/views/admin/index.html.erb
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
  <tbody>
    <tr>
      <td valign="middle">
        <div class="container full-spaced full-spaced-bottom">
          <div class="row">
            <div class="col-xs-12">
              <h1>Pipecandy Admin</h1>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-sm-8 col-xs-12 half-spaced">
              <table class="table">
                <tbody>
                  <tr>
                    <td colspan="2" style="border: 0 none;">
                      <h4>Follow/Unfollow Feature</h4>
                    </td>
                  </tr>
                  <tr>
                    <td style="border: 0 none;" width="150">For twitter </td>
                    <td style="border: 0 none;" width="20">:</td>
                    <td style="border: 0 none;" width="250">
                      <a href="<%= twitter_path %>" target="_blank">Twitter Auto Follow/Unfollow</a>
                    </td>
                  </tr>
                  <tr>
                    <td style="border: 0 none;" width="150">For inbound </td>
                    <td style="border: 0 none;" width="20">:</td>
                    <td style="border: 0 none;" width="250">
                      <a href="<%= inbound_path %>" target="_blank">Inbound Auto Follow/Unfollow</a>
                    </td>
                  </tr>
                  <tr>
                    <td style="border: 0 none;" width="150">AWS</td>
                    <td style="border: 0 none;" width="20">:</td>
                    <td style="border: 0 none;" width="250">
                      <a href="/admin/aws/all" target="_blank">AWS Tracking</a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <% unless @concierge.blank? %>
            <div class="row">
              <div class="col-xs-12 spaced">
                <h3>Concierge Emails</h3>
              </div>
              <div class="col-xs-12 half-spaced">
                <strong>Download Report: &nbsp;<a href="./admin.csv" download="Concierge.csv">CSV</a> | <a href="./admin.xls" download="Concierge.xls">XLS</a></strong>
              </div>
              <div class="col-xs-12 half-spaced">
                <a class="btn btn-primary concierge-table-update">Refresh table</a>
              </div>
              <div class="col-xs-12 spaced" id="concierge_datatable">
                <div class="row">
                  <div class="col-sm-6">
                    <input id="conciergeSearch" type="text" placeholder="Search" />
                  </div>
                  <div class="col-sm-6 text-right">
                    <div class="dropdown" style="padding-top: 7px;">
                      <label id="dataTablesInfo"></label>
                      <button class="btn dropdown-toggle custom-dropdown-btn" type="button" id="dataTablesLength" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span></button>
                      <ul class="dropdown-menu custom-dropdown-menu" aria-labelledby="dataTablesLength">
                        <li style="padding: 6px 0px;">Show up to:</li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(30);">&nbsp;&nbsp;10 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(60);">&nbsp;&nbsp;20 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(120);">&nbsp;&nbsp;40 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(-1);">&nbsp;&nbsp;All items</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <table id="concierge" class="table" data-source="/admin.json">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Name</th>
                      <th>E-Mail</th>
                      <th>Company</th>
                      <th>description</th>
                      <th>Date</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/twitter.html.erb
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
  <tbody>
    <tr>
      <td valign="middle">
        <div class="container full-spaced full-spaced-bottom">
          <div class="row">
            <div class="col-lg-6 col-md-7 col-sm-8 col-xs-11 col-centered">
              <h2 class="text-center no-margin">Twitter Portal</h2>
              <p class="text-center no-margin">Use the tabs below to toggle between Twitter Tweets &amp; Twitter Users Datatable.</p> 

              <%= form_tag twitter_path, method: :post, id: "twitter_form", class: "spaced spaced-bottom" do %>
                <div class="input-group">
                  <%= text_field_tag :username, "", class: "form-control sharp-corners", required: true, placeholder: "Twitter Username (PipeCandyHQ)", "data-parsley-error-message" => "Please enter the twitter username only!.", "data-parsley-errors-container" => "#twitter_username_error" %>
                  <span class="input-group-btn">
                    <%= submit_tag "Proceed!", id: "twitter_form_submit", class: "btn btn-default sharp-corners" %>
                  </span>
                </div>
                <div id="twitter_username_error"></div>
              <% end %>
            </div>
          </div>
          <br><br>
          <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <ul class="nav nav-tabs nav-justified">
              <% unless @twitter_tweets_all.blank? %>
                <li class="active"><a data-toggle="tab" href="#tweets">Twitter Tweets</a></li>
              <% end %>
              <% unless @twitter_followers.blank? %>
                <li><a data-toggle="tab" href="#table">Twitter Followers Table</a></li>
              <% end %>
            </ul>
            </div>
          </div>
           <div class="tab-content">         
                        <% unless @twitter_tweets_all.blank? %>

           <div id="tweets" class="tab-pane fade in active">
             <div class="row full-spaced">
                          <div class="col-md-10 col-sm-10 col-xs-12 col-centered spaced" id="twitter_tweet_all_datatable">
                              <div class="col-sm-12">
                                <input id="twitterTweetAllSearch" type="text" placeholder="Search" />
                              </div>
                              <div class="col-sm-12 text-right">
                                <div class="dropdown" style="padding-top: 7px;">
                                  <label id="dataTablesInfo0"></label>
                                  <button class="btn dropdown-toggle custom-dropdown-btn" type="button" id="dataTablesLength0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span></button>
                                  <ul class="dropdown-menu custom-dropdown-menu" aria-labelledby="dataTablesLength0">
                                    <li style="padding: 6px 0px;">Show up to:</li>
                                    <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(10);">&nbsp;&nbsp;10 items</a></li>
                                    <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(20);">&nbsp;&nbsp;20 items</a></li>
                                    <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(40);">&nbsp;&nbsp;40 items</a></li>
                                    <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(80);">&nbsp;&nbsp;80 items</a></li>
                                    <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(100);">&nbsp;&nbsp;100 items</a></li>
                                  </ul>
                                </div>
                              </div>
                            <table id="twitter_tweets_all" class="table table-bordered" data-source="/admin/twitter-tweets-all.json">
                              <thead>
                                <tr>
                                  <th>Tweet</th>
                                  <th>User</th>
                                  <th>Links</th>
                                </tr>
                              </thead>
                              <tbody>
                              </tbody>
                            </table>
                          </div>
                        </div>           

           </div>
                         <% end %>


           <div id="table" class="tab-pane fade in">
          <% unless @twitter_users.blank? %>
            <div class="row full-spaced">
              <div class="col-md-9 col-sm-10 col-xs-12 col-centered spaced" id="twitter_datatable">
                <div class="row-height">
                  <div class="col-height col-middle">
                    <%= label_tag "screen_name", "Select Twitter Name" %>
                    <div class="select-style half-spaced">
                      <%= select_tag "screen_name[]", options_from_collection_for_select(@twitter_users, :id, :name), include_blank: "All", id: "twitterScreenName", placeholder: "Select the username" %>
                    </div>
                  </div>
                  <div class="col-height col-bottom text-right" id="twitterUpdateLink">
                  </div>
                </div>
                <div class="row spaced">
                  <div class="col-sm-6">
                    <input id="twitterFollowerSearch" type="text" placeholder="Search" />
                  </div>
                  <div class="col-sm-6 text-right">
                    <div class="dropdown" style="padding-top: 7px;">
                      <label id="dataTablesInfo"></label>
                      <button class="btn dropdown-toggle custom-dropdown-btn" type="button" id="dataTablesLength" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span></button>
                      <ul class="dropdown-menu custom-dropdown-menu" aria-labelledby="dataTablesLength">
                        <li style="padding: 6px 0px;">Show up to:</li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(10);">&nbsp;&nbsp;10 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(20);">&nbsp;&nbsp;20 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(40);">&nbsp;&nbsp;40 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(80);">&nbsp;&nbsp;80 items</a></li>
                        <li><a href="javascript:void(0);" onclick="$.fn.changeDataTableLength(100);">&nbsp;&nbsp;100 items</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <table id="twitter_followers" class="table table-bordered" data-source="/admin/twitter.json">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Following</th>
                      <th>Follow Back</th>
                      <th>Date Processed</th>
                      <th class="text-center" style="padding-right: 0px;">Link</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
          </div>
          </div>
        </div>
      </td>
    </tr>
  </tbody>
</table>